### ISSUE TITLE
add detail page for each website/endpoint

### ISSUE THREAD

**Issue by elianiva** [teknologi-umum/semya#4]
currently there's only overview page, we should make each page for each endpoint/website that's being monitored. Get the data from backend through SSE.

**Comment by aldy505** [comment]
the detail page should read from the config.json file, the backend won't provide any detailed information about that. you should keep that in mind.

and also think about what if the config changed midway, where as there are some data that's been written previously. so, in the first day, you have the endpoint of:
```json
{
  "name": "Polarite",
  "url": "https://polarite.teknologiumum.com/healthz",
  "description": "Blabla"
}
```

what would happened if the URL changes? what would happened if the name changes?

as the backend developer, I can only assure you that the URL would be consistent, you should cross-check everything based on the URL that you get from the config.json AND from the API response.
